config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  resources :saves
  root to: "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/save.rb
class Save < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/saves_controller.rb
class SavesController < ApplicationController
  before_action :set_safe, only: [:show, :edit, :update, :destroy]

  # GET /saves
  # GET /saves.json
  def index
    @saves = Save.all
  end

  # GET /saves/1
  # GET /saves/1.json
  def show
  end

  # GET /saves/new
  def new
    @safe = Save.new
  end

  # GET /saves/1/edit
  def edit
  end

  # POST /saves
  # POST /saves.json
  def create
    @safe = Save.new(safe_params)

    respond_to do |format|
      if @safe.save
        format.html { redirect_to @safe, notice: 'Save was successfully created.' }
        format.json { render :show, status: :created, location: @safe }
      else
        format.html { render :new }
        format.json { render json: @safe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saves/1
  # PATCH/PUT /saves/1.json
  def update
    respond_to do |format|
      if @safe.update(safe_params)
        format.html { redirect_to @safe, notice: 'Save was successfully updated.' }
        format.json { render :show, status: :ok, location: @safe }
      else
        format.html { render :edit }
        format.json { render json: @safe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saves/1
  # DELETE /saves/1.json
  def destroy
    @safe.destroy
    respond_to do |format|
      format.html { redirect_to saves_url, notice: 'Save was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_safe
      @safe = Save.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def safe_params
      params.require(:safe).permit(:store, :info)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/saves_helper.rb
module SavesHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proto2ReactRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_react' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= react_component('GameWindow', prerender: true) %>

app/views/saves/_form.html.erb
<%= form_with(model: safe, local: true) do |form| %>
  <% if safe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(safe.errors.count, "error") %> prohibited this safe from being saved:</h2>

      <ul>
      <% safe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :store %>
    <%= form.text_field :store %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_field :info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/saves/edit.html.erb
<h1>Editing Safe</h1>

<%= render 'form', safe: @safe %>

<%= link_to 'Show', @safe %> |
<%= link_to 'Back', saves_path %>

app/views/saves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Saves</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saves.each do |safe| %>
      <tr>
        <td><%= safe.store %></td>
        <td><%= safe.info %></td>
        <td><%= link_to 'Show', safe %></td>
        <td><%= link_to 'Edit', edit_safe_path(safe) %></td>
        <td><%= link_to 'Destroy', safe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Safe', new_safe_path %>

app/views/saves/new.html.erb
<h1>New Safe</h1>

<%= render 'form', safe: @safe %>

<%= link_to 'Back', saves_path %>

app/views/saves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @safe.store %>
</p>

<p>
  <strong>Info:</strong>
  <%= @safe.info %>
</p>

<%= link_to 'Edit', edit_safe_path(@safe) %> |
<%= link_to 'Back', saves_path %>